### ISSUE TITLE
Last version

### ISSUE THREAD

**Issue by stastnypremysl** [Patryk27/lxd-snapper#1]
Hello. 

I don't understand your versioning in tags. What is the last version please?

I would like to add package to Gentoo repo and I need to know, which version.

Thanks.
Přemysl

**Comment by stastnypremysl** [comment]
EDIT: There is a problem with the date of tags. The 0.1 tag is newer than 1.0 by the date.

**Comment by Patryk27** [comment]
Hi, sorry for late answer - for some reason GitHub didn't send me any notification 😢 

The newest version is tagged by `v1.0` at `17 Oct 2020`, with `v0.1` (the previous release) being tagged at `22 Jul 2019`, at least according to https://github.com/Patryk27/lxd-snapper/tags.

Could you show me where the v0.1 tag is display as newer?

**Comment by stastnypremysl** [comment]
Hello.

Thanks for your answer. There was probably some bug, which made me see 2020 as 2017. It's gone now.
