### ISSUE TITLE
Volume selection

### ISSUE THREAD

**Issue by stastnypremysl** [Patryk27/lxd-snapper#3]
Is there any way, how to include or exclude specific volume from being snapshoted please?

For example, I don't want /tmp being snapshoted.

Thanks.

**Comment by Patryk27** [comment]
Hi,

`lxd-snapper` underneath calls `lxc snapshot`, which - as far as I'm aware - doesn't allow to choose a particular volume.

That being said, I think it should be possible to exclude a certain directory if you mounted it manually:
```bash
$ mkdir /tmp/my-container
$ lxc config device add my-container tmp disk source=/tmp/my-container path=/tmp
```
(this bind-mounts `/tmp/my-container` from host as `/tmp` inside the container.)

**Comment by stastnypremysl** [comment]
Hello.

Thanks. You are right. I didn't expected them to not support such elementary functionality as selecting a volume.
