### ISSUE TITLE
Set Maximum Size of Snapshots?

### ISSUE THREAD

**Issue by stanleyshly** [Patryk27/lxd-snapper#7]
In normal snapper, the maximum snapshot size can be set as a fraction of the maximum size of the filesystem. Would you be willing to provide an example in the example config in the readme about how to set this up in lxd-snapper?

**Comment by Patryk27** [comment]
Hi, I'm afraid this is not configurable - lxd-snapper is mostly a wrapper around LXC/LXD commands, and they don't seem to be supporting this kind of limit.
