### ISSUE TITLE
new 'Ready' state

### ISSUE THREAD

**Issue by aivanise** [Patryk27/lxd-snapper#9]
since 5.5 LXD has a new user controlled 'Ready' state, any way we can handle that, it should be a quick change

Sep 28 12:00:46 lxd10.2e-systems.com lxd-snapper[726652]:         2: unknown variant `Ready`, expected one of `Aborting`, `Running`, `Starting`, `Stopped`, `Stopping` at line 1 column 2157213

more about ready state at https://discuss.linuxcontainers.org/t/lxd-instance-ready-state/14657

**Comment by Patryk27** [comment]
Hi,

Thanks for reporting - your commit looks nice, feel free to create a pull request if you want 🙂

**Comment by aivanise** [comment]
Sure, here you go :)
